50 compiler les fichiers markdown en html
dil-classroom/projet-coduri_fontaine_grunder_jeanrenaud pull request #52
Opened 2022-05-12 10:45 UTC by LucaCoduriV

Cette fois-ci le test est plus complet.

2022-05-24 15:31 UTC, chloefont requested changes
## BuildCommand
### Fonction parseAndCreateFile : 
- Commentaire "This method can be faster if the files are copied only once. But it is not." pas très clair.
- Manque de commentaires dans la dernière partie de la fonction.
- Ligne 112 : au lieu de faire un nouveau try, tu peux le laisser dans le même bloc et faire un autre catch qui intercepte la seconde erreur.

## Markdown2htmlParser
Il manque quelques commentaires pour bien comprendre les fonctions.

2022-05-25 17:35 UTC, LucaCoduriV commented
Je vais laisser le try catch car il me permet de faire un dispose automatiquement

2022-05-25 18:03 UTC, LucaCoduriV commented
Voila, j'ai fais les changements.

2022-05-25 21:43 UTC, chloefont approved these changes
Tout est ok pour moi, très bon travail !

2022-05-25 21:43 UTC, merged